config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope "(:locale)", locale: /en|fr/ do
    root "home_pages#index"
    resources :customers

    namespace :admin do
      root :to => "users#index"
      resources :users
      resources :slider_images, only: :update
      resources :engagements
      resources :producers, except: :show
      resources :products, except: :show
      resources :customers, only: [:index, :show, :destroy]

      resource :slider_shows, only: [:show, :edit, :update]
      resource :d3s_informations, only: [:show, :edit, :update]
      resource :origines, only: [:show, :edit, :update]
      resource :popups, only: [:show, :edit, :update]
      resource :facilities, only: [:show, :edit, :update]
      resource :producters, only: [:show, :edit, :update]
      resource :module_themes, only: [:show, :edit, :update]
    end
  end
end

app/models/engagement.rb
class Engagement < ApplicationRecord
  has_many :engagement_translations

  accepts_nested_attributes_for :engagement_translations

  delegate :title, :content, to: :localize, prefix: true, allow_nil: true

  def localize
    localize = engagement_translations.find_by language: I18n.locale
  end

  def by_localize locale
    by_localize = engagement_translations.find_by language: locale
  end
end

app/controllers/admin/engagements_controller.rb
class Admin::EngagementsController < AdminController
  load_and_authorize_resource

  before_action :load_engagement, except: [:index, :new, :create]

  def index
    @engagements = Engagement.all.includes(:engagement_translations)
  end

  def show
  end

  def new
    @engagement = Engagement.new
    build_translation @engagement
  end

  def create
    @engagement = Engagement.new engagement_params
    if @engagement.save
      flash[:success] = t ".success"
      redirect_to admin_engagements_path
    else
      flash.now[:failed] = t ".failed"
      render :new
    end
  end

  def edit
    @engagement_translations = @engagement.engagement_translations
  end

  def update
    if @engagement.update_attributes engagement_params
      flash[:success] = t ".success"
      redirect_to admin_engagements_path
    else
      flash.now[:failed] = t ".failed"
      render :edit
    end
  end

  def destroy
    if @engagement.destroy
      flash[:success] = t ".success"
    else
      flash[:failed] = t ".failed"
    end
    redirect_to admin_engagements_path
  end

  private
  def engagement_params
    params.require(:engagement).permit :title, :content, engagement_translations_attributes: [:id, :language, :title, :content]
  end

  def load_engagement
    @engagement = Engagement.includes(:engagement_translations).find(params[:id])
  end

  def build_translation engagement
    @engagement_translations = []
    Settings.translation_languages.each do |lang|
      @engagement_translations << engagement.engagement_translations.new(language: lang)
    end
    @engagement_translations
  end
end

app/views/admin/engagements/_form.html.slim
= f.fields_for :engagement_translations, engagement_translations do |ff|
  = ff.hidden_field :language
  p
    = tranlations_version ff.object.language
  .form-group
    = ff.label :title, class: "col-md-2 control-label" do
      = t ".title"
    .col-md-10
      = ff.text_field :title, class: "form-control"

  .form-group
    = ff.label :content, class: "col-md-2 control-label" do
      = t ".content"
    .col-md-10
      = ff.text_area :content, class: "form-control", rows: 10
  
  hr

app/views/admin/engagements/edit.html.slim
section.content
  .row
    .col-md-8.col-md-offset-2
      .box.box-success
        .box-header.with-border.text-center
          h3.box-title= t('.edit_engagement')
        .box-body
          = form_for [:admin, @engagement], html: {class: "form-horizontal"} do |f|
            = render "form", f: f, engagement_translations: @engagement_translations
            = f.submit t(".submit"), class: "form-control btn btn-block btn-primary btn-flat"

app/views/admin/engagements/index.html.slim
- provide :title, t('.users')
section.content-header
  = link_to t('.new_engagement'), new_admin_engagement_path, class: 'btn bg-purple margin'

- if @engagements.any?
  section.content
    .row
      .col-xs-12
        .box.box-info
          .box-header
            h3.box-title Engagement list
          .box-body
            table.table.table-bordered.table-striped
              thead
                th = t ".index"
                - Settings.translation_languages.each do |lang|
                  th = t ".title", language: tranlations_name(lang)
                  th = t ".content", language: tranlations_name(lang)
                th = t ".action"
              tbody
                - @engagements.each_with_index do |engagement, index|
                  tr
                    td = index + 1
                    - Settings.translation_languages.each do |lang|
                      - engagement_translation = engagement.by_localize(lang)
                      td = engagement_translation.title
                      td = simple_format engagement_translation.content
                    td
                      = link_to t(".show"), admin_engagement_path(engagement), class: "btn label label-success"
                      | &nbsp;
                      = link_to t(".edit"), edit_admin_engagement_path(engagement), class: "btn label label-info"
                      | &nbsp;
                      = link_to t(".delete"), admin_engagement_path(engagement), method: :delete,
                        "data-confirm": t(".confirm_delete_engagement"), class: "btn label label-danger"

app/views/admin/engagements/new.html.slim
section.content
  .row
    .col-md-8.col-md-offset-2
      .box.box-success
        .box-header.with-border.text-center
          h3.box-title= t('.create_engagement')
        .box-body
          = form_for [:admin, @engagement], html: {class: "form-horizontal"} do |f|
            = render "form", f: f, engagement_translations: @engagement_translations
            = f.submit t(".submit"), class: "form-control btn btn-block btn-primary btn-flat"