config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope "(:locale)", locale: /en|fr/ do
    root "home_pages#index"
    resources :customers

    namespace :admin do
      root :to => "users#index"
      resources :users
      resources :slider_images, only: :update
      resources :engagements
      resources :producers, except: :show
      resources :products, except: :show
      resources :customers, only: [:index, :show, :destroy]

      resource :slider_shows, only: [:show, :edit, :update]
      resource :d3s_informations, only: [:show, :edit, :update]
      resource :origines, only: [:show, :edit, :update]
      resource :popups, only: [:show, :edit, :update]
      resource :facilities, only: [:show, :edit, :update]
      resource :producters, only: [:show, :edit, :update]
      resource :module_themes, only: [:show, :edit, :update]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user, controller_namespace)
    user ||= User.new

    if controller_namespace == "admin"
      case user.role
      when 'admin'
        can :manage, :all
      when 'mod'
        can [:read, :edit], User, role: 1, id: user.id
        can :manage, Customer
        can :manage, D3sInformation
        can :manage, Engagement
        can :manage, Facility
        can :manage, ModuleTheme
        can :manage, Origine
        can :manage, Popup
        can :manage, Producer
        can :manage, Product
        can :manage, Producter
        can :manage, SliderShow
        can :manage, SliderImage
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  CREATE_ATTRIBUTE = [:name, :email, :message, :company]

  validates :name, :email, :message, :company, presence: true
end

app/models/d3s_information.rb
class D3sInformation < ApplicationRecord
  mount_uploader :image_1, ImageUploader
  mount_uploader :image_2, ImageUploader

  has_many :d3s_information_languages

  accepts_nested_attributes_for :d3s_information_languages, allow_destroy: true

  delegate :title_1, :title_2, :des_1, :des_2, :des_middle, to: :localize, prefix: true, allow_nil: true

  def localize
    localize = d3s_information_languages.find_by language: I18n.locale
  end

  UPDATE_D3S_INFOMATION_ATTRIBUTES = [:image_1, :image_2, d3s_information_languages_attributes: 
  	[:id, :des_information_id, :title_1, :title_2, :des_1, :des_2, :des_middle, :_destroy]]
end

app/models/engagement.rb
class Engagement < ApplicationRecord
  has_many :engagement_translations

  accepts_nested_attributes_for :engagement_translations

  delegate :title, :content, to: :localize, prefix: true, allow_nil: true

  def localize
    localize = engagement_translations.find_by language: I18n.locale
  end

  def by_localize locale
    by_localize = engagement_translations.find_by language: locale
  end
end

app/models/facility.rb
class Facility < ApplicationRecord
  mount_uploader :image, ImageUploader
  mount_uploader :video, VideoUploader

  has_many :facility_languages

  accepts_nested_attributes_for :facility_languages, allow_destroy: true

  UPDATE_FACILITY_ATTRIBUTES = [:image, :video, facility_languages_attributes: [:id, :facility_id, :language,
    :left_text_1, :left_text_2, :right_text_1, :right_text_2, :right_text_3]]

  delegate :left_text_1, :left_text_2, :right_text_1, :right_text_2, :right_text_3, to: :localize, prefix: true, allow_nil: true

  def localize
    localize = facility_languages.find_by language: I18n.locale
  end
end

app/models/facility_language.rb
class FacilityLanguage < ApplicationRecord
  belongs_to :facility
end

app/models/module_theme.rb
class ModuleTheme < ApplicationRecord

  has_many :module_theme_languages

  accepts_nested_attributes_for :module_theme_languages, allow_destroy: true

  UPDATE_MODULE_THEME_ATTRIBUTES = [:name, module_theme_languages_attributes:
    [:id, :module_theme_id, :language, :img_about, :img_enga, :img_enga_producter,
     :img_enga_quality, :img_origine, :img_product, :img_producter, :img_facility,
     :img_contact, :_destroy]]
end

app/models/origine.rb
class Origine < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :origine_languages

  accepts_nested_attributes_for :origine_languages, allow_destroy: true

  UPDATE_ORIGINE_ATTRIBUTES = [:image, origine_languages_attributes: 
  	[:id, :origine_id, :left_text_1, :left_text_2, :left_text_3, :right_title_1, :right_title_2,
  	:right_title_3, :right_des_1, :right_des_2, :right_des_3, :_destroy]]
end

app/models/origine_language.rb
class OrigineLanguage < ApplicationRecord
  belongs_to :origine
end

app/models/popup.rb
class Popup < ApplicationRecord
  has_many :popup_translations

  accepts_nested_attributes_for :popup_translations

  delegate :title, :content, to: :localize, prefix: true, allow_nil: true

  def localize
    localize = popup_translations.find_by language: I18n.locale
  end
end

app/models/popup_translation.rb
class PopupTranslation < ApplicationRecord
  belongs_to :popup

  enum language: Settings.translation_languages.map(&:to_sym)
end

app/models/producer.rb
class Producer < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :producer_translations

  accepts_nested_attributes_for :producer_translations

  delegate :title, to: :localize, prefix: true, allow_nil: true

  def localize
    localize = producer_translations.find_by language: I18n.locale
  end

  def by_localize locale
    by_localize = producer_translations.find_by language: locale
  end
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :product_translations

  accepts_nested_attributes_for :product_translations

  delegate :title, :content, to: :localize, prefix: true, allow_nil: true

  def localize
    localize = product_translations.find_by language: I18n.locale
  end

  def by_localize locale
    by_localize = product_translations.find_by language: locale
  end
end

app/models/producter.rb
class Producter < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :producter_languages

  accepts_nested_attributes_for :producter_languages, allow_destroy: true

  UPDATE_PRODUCTER_ATTRIBUTES = [:image, producter_languages_attributes: 
    [:id, :producter_id, :left_text_1, :left_text_2, :right_text_1, :right_text_2,
    :right_text_3, :_destroy]]
end

app/models/producter_language.rb
class ProducterLanguage < ApplicationRecord
  belongs_to :producter
end

app/models/slider_image.rb
class SliderImage < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :slider_show

  validates :sort_index, uniqueness: { scope: :slider_show_id, allow_blank: true }
end

app/models/slider_show.rb
class SliderShow < ApplicationRecord

  has_many :slider_images
  has_many :slider_show_translations

  accepts_nested_attributes_for :slider_images, allow_destroy: true
  accepts_nested_attributes_for :slider_show_translations, allow_destroy: true

  delegate :title_1, :title_2, to: :localize, prefix: true, allow_nil: true

  def localize
    localize = slider_show_translations.find_by language: I18n.locale
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ADMIN_CREATE_ATTRIBUTE = [:email, :password, :password_confirmation, :role]
  UPDATE_ATTRIBUTE = [:name, :role]

  enum role: {admin: 0, mod: 1}

  attr_accessor :admin_create_user
end

app/helpers/application_helper.rb
module ApplicationHelper
  FLASH_TYPE = {
    success: 'alert-successed', failed: 'alert-failed', error: 'alert-failed',
    notice: 'alert-successed', alert: 'alert-info'
  }

 # def full_title(page_title = '')
 #    return t('app_name') if page_title.blank?
 #    "#{page_title} | #{t('app_name')}"
 #  end

	def full_title(page_title = '')
    return "D3S" if page_title.blank?
    "Page | D3S"
  end

  def flash_class flash_type
    FLASH_TYPE[flash_type] || flash_type.to_s
  end

  def show_field_error form, attribute
    error_field = <<-HTML
      <div class="md-input-message-animation">
        #{t('activerecord.errors.models')[form.object.class.name.downcase
          .to_sym][:attributes][attribute]} #{form.object.errors[attribute].first}
      </div>
    HTML
    error_field.html_safe if form.object.errors[attribute].present?
  end

  def tranlations_version code
    "#{Settings.languages.to_h[code.to_sym]} version"
  end

  def tranlations_name code
    Settings.languages.to_h[code.to_sym]
  end
end

app/views/layouts/admin/_footer.html.slim
footer.main-footer
  .pull-right.hidden-xs
    b Version &nbsp;
    | 1.0.0
  strong
    | Copyright © 2018
    a href=""  D3S &nbsp;
  | All rights
  | reserved.

app/views/layouts/admin/_header.html.slim
header.main-header
  a.logo href=admin_root_path 
    span.logo-mini
      b> D
      | 3S
    span.logo-lg
      b> Admin
      | D3S
  nav.navbar.navbar-static-top
    a.sidebar-toggle data-toggle="push-menu" href="#" role="button" 
      span.sr-only Toggle navigation
      span.icon-bar
      span.icon-bar
      span.icon-bar
    .navbar-custom-menu
      ul.nav.navbar-nav
        li.dropdown.notifications-menu
          a.dropdown-toggle data-toggle="dropdown" href="#" id="tooltip"
            i.fa.fa-bell-o
            span.label.label-warning 10
          ul.dropdown-menu
            li.header You have 10 notifications
            li
              ul.menu
                li
                  a href="#" 
                    i.fa.fa-users.text-aqua
                    | 5 new members joined today
            li.footer
              a href="#"  View all]
              
        li.dropdown.user.user-menu
          a.dropdown-toggle data-toggle="dropdown" href="#"
            = image_tag 'no_image.png', size: '30x30', class: "img-circle user-image", alt: "User Avatar"
            span.hidden-xs
              = current_user.name
          ul.dropdown-menu
            li.user-header
              = image_tag 'no_image.png', size: '100x100', class: "img-circle"
              p
                = current_user.name
                small
                  | Registed from #{current_user.created_at.strftime("%Y/%m/%d %H:%M")}
            li.user-footer
              .pull-left
                = link_to "Profile", admin_user_path(current_user), class: "btn btn-default btn-flat"
              .pull-right
                = link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-default btn-flat"

app/views/layouts/admin/_left_bar.html.slim
aside.main-sidebar
  section.sidebar
    .user-panel
      .pull-left.image
        - if current_user.user_avatar.present?
          = image_tag current_user.user_avatar.url(:thumb), class: "img-circle", alt: "User Avatar"
        - else
          = image_tag 'no_image.png', size: '20x20'
      .pull-left.info
        p
          = current_user.name
        a href="#"
          i.fa.fa-circle.text-success
          | Online
    form.sidebar-form action="#" method="get"
      .input-group
        input.form-control name="q" placeholder="Search..." type="text" /
        span.input-group-btn
          button#search-btn.btn.btn-flat name="search" type="submit"
            i.fa.fa-search
    ul.sidebar-menu data-widget="tree"
      li.header MAIN NAVIGATION
      li
        = link_to admin_users_path, id: "left-bar-admin-user" do
          i.fa.fa-user
          span = t ".user"
      li
        = link_to admin_popups_path, id: "left-bar-admin-popups" do
          i.fa.fa-upload
          span = t ".popups"
      li
        = link_to admin_slider_shows_path, id: "left-bar-admin-slider" do
          i.fa.fa-image
          span = t ".slider_show"
      li
        = link_to admin_d3s_informations_path, id: "left-bar-admin-about" do
          i.fa.fa-sticky-note
          span = t ".d3s_information"
      li
        = link_to admin_engagements_path, id: "left-bar-admin-engagement" do
          i.fa.fa-american-sign-language-interpreting
          span = t ".engagement"
      li
        = link_to admin_producers_path, id: "left-bar-admin-producers" do
          i.fa.fa-industry
          span = t ".producer"
      li
        = link_to admin_origines_path, id: "left-bar-admin-origine" do
          i.fa.fa-star
          span = t ".origine"
      li
        = link_to admin_products_path, id: "left-bar-admin-engagement" do
          i.fa.fa-apple
          span = t ".products"
      li
        = link_to admin_producters_path, id: "left-bar-admin-facilities" do
          i.fa.fa-users
          span = t ".producters"
      li
        = link_to admin_facilities_path, id: "left-bar-admin-facilities" do
          i.fa.fa-cubes
          span = t ".facilities"
      li
        = link_to admin_customers_path, id: "left-bar-admin-customer" do
          i.fa.fa-address-book
          span = t ".customers"
      li
        = link_to admin_module_themes_path, id: "left-bar-admin-module-theme" do
          i.fa.fa-image
          span = t ".theme"

app/views/layouts/admin/_shim.html.slim
/![if lt IE 9]
  | <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"
  | </script

app/views/shared/_breadcrumb.html.slim
section.content-header.breadcrumb
  ol.breadcrumb
    li
      a href=admin_root_path 
        i.fa.fa-dashboard Home
    li
      a href=send("admin_#{params[:controller].split("/").last}_path") = params[:controller].split("/").last.camelize
    li.active= params[:action]

app/views/shared/_messages.html.slim
- flash.each do |type, message|
  - if message
    div class=("alert #{flash_class type.to_sym} fade in flash-notice") 
      a.close aria-hidden="true" data-dismiss="alert" href="#"  ×
      p.text-center.flash-message= message