config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope "(:locale)", locale: /en|fr/ do
    root "home_pages#index"
    resources :customers

    namespace :admin do
      root :to => "users#index"
      resources :users
      resources :slider_images, only: :update
      resources :engagements
      resources :producers, except: :show
      resources :products, except: :show
      resources :customers, only: [:index, :show, :destroy]

      resource :slider_shows, only: [:show, :edit, :update]
      resource :d3s_informations, only: [:show, :edit, :update]
      resource :origines, only: [:show, :edit, :update]
      resource :popups, only: [:show, :edit, :update]
      resource :facilities, only: [:show, :edit, :update]
      resource :producters, only: [:show, :edit, :update]
      resource :module_themes, only: [:show, :edit, :update]
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :product_translations

  accepts_nested_attributes_for :product_translations

  delegate :title, :content, to: :localize, prefix: true, allow_nil: true

  def localize
    localize = product_translations.find_by language: I18n.locale
  end

  def by_localize locale
    by_localize = product_translations.find_by language: locale
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  load_and_authorize_resource

  before_action :load_product, except: [:index, :new, :create]

  def index
    @products = Product.all.includes(:product_translations)
  end

  def show
  end

  def new
    @product = Product.new
    build_translation @product
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:success] = t ".success"
      redirect_to admin_products_path
    else
      flash.now[:failed] = t ".failed"
      render :new
    end
  end

  def edit
    @product_translations = @product.product_translations
  end

  def update
    if @product.update_attributes product_params
      flash[:success] = t ".success"
      redirect_to admin_products_path
    else
      flash.now[:failed] = t ".failed"
      render :edit
    end
  end

  def destroy
    if @product.destroy
      flash[:success] = t ".success"
    else
      flash[:failed] = t ".failed"
    end
    redirect_to admin_products_path
  end

  private
  def product_params
    params.require(:product).permit :image, product_translations_attributes: [:id, :language, :title, :content]
  end

  def load_product
    @product = Product.includes(:product_translations).find(params[:id])
  end

  def build_translation product
    @product_translations = []
    Settings.translation_languages.each do |lang|
      @product_translations << product.product_translations.new(language: lang)
    end
    @product_translations
  end
end

app/views/admin/products/_form.html.slim
.form-group
  = f.label :image, class: "col-md-2 control-label" do
    = t ".image"
  .col-md-10
    = image_tag f.object.image, class: "preview_image", id: "img_product" if f.object.image
    = f.file_field :image, class: "form-control", onchange: "readURL(this, '#img_product');"
    .text-danger.mg-t-5 Size: 458 x 305(px)

hr

= f.fields_for :product_translations, product_translations do |ff|
  = ff.hidden_field :language
  p
    = tranlations_version ff.object.language
  .form-group
    = ff.label :title, class: "col-md-2 control-label" do
      = t ".title"
    .col-md-10
      = ff.text_field :title, class: "form-control"

  .form-group
    = ff.label :title, class: "col-md-2 control-label" do
      = t ".content"
    .col-md-10
      = ff.cktext_area :content, class: "form-control"

  hr

app/views/admin/products/edit.html.slim
section.content
  .row
    .col-md-8.col-md-offset-2
      .box.box-success
        .box-header.with-border.text-center
          h3.box-title= t('.edit_product')
        .box-body
          = form_for [:admin, @product], html: {class: "form-horizontal"} do |f|
            = render "form", f: f, product_translations: @product_translations
            = f.submit t(".submit"), class: "form-control btn btn-block btn-primary btn-flat"

app/views/admin/products/index.html.slim
- provide :title, t('.products')
section.content-header
  = link_to t('.new_product'), new_admin_product_path, class: 'btn bg-purple margin'

- if @products.any?
  section.content
    .row
      .col-xs-12
        - Settings.translation_languages.each do |lang|
          .box.box-info
            .box-header
              h3.box-title
                p = tranlations_version lang
              .box-body
                table.table.table-bordered.table-striped
                  thead
                    th = t ".index"
                    th = t ".image"
                    th = t ".title"
                    th = t ".content"
                    th = t ".action"
                  tbody
                    - @products.each_with_index do |product, index|
                      tr
                        td = index + 1
                        td
                          = link_to product&.image_url, "target": "blank" do
                            = image_tag product&.image, class: "image_in_table"
                        - product_translation = product.by_localize(lang)
                        td = raw product_translation&.title
                        td = raw product_translation&.content
                        td
                          = link_to t(".edit"), edit_admin_product_path(product), class: "btn label label-info"
                          | &nbsp;
                          = link_to t(".delete"), admin_product_path(product), method: :delete,
                            "data-confirm": t(".confirm_delete_product"), class: "btn label label-danger"

app/views/admin/products/new.html.slim
section.content
  .row
    .col-md-8.col-md-offset-2
      .box.box-success
        .box-header.with-border.text-center
          h3.box-title= t('.create_product')
        .box-body
          = form_for [:admin, @product], html: {class: "form-horizontal"} do |f|
            = render "form", f: f, product_translations: @product_translations
            = f.submit t(".submit"), class: "form-control btn btn-block btn-primary btn-flat"