config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope "(:locale)", locale: /en|fr/ do
    root "home_pages#index"
    resources :customers

    namespace :admin do
      root :to => "users#index"
      resources :users
      resources :slider_images, only: :update
      resources :engagements
      resources :producers, except: :show
      resources :products, except: :show
      resources :customers, only: [:index, :show, :destroy]

      resource :slider_shows, only: [:show, :edit, :update]
      resource :d3s_informations, only: [:show, :edit, :update]
      resource :origines, only: [:show, :edit, :update]
      resource :popups, only: [:show, :edit, :update]
      resource :facilities, only: [:show, :edit, :update]
      resource :producters, only: [:show, :edit, :update]
      resource :module_themes, only: [:show, :edit, :update]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ADMIN_CREATE_ATTRIBUTE = [:email, :password, :password_confirmation, :role]
  UPDATE_ATTRIBUTE = [:name, :role]

  enum role: {admin: 0, mod: 1}

  attr_accessor :admin_create_user
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  load_and_authorize_resource

  before_action :load_user_data, only: [:edit, :update, :show, :destroy]

  def index
    if current_user.admin?
      return @users = User.all
    else
      return @users = User.mod
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    @user.admin_create_user = true
    if @user.save
      UserMailer.send_password_to_user(@user.email, @user.password).deliver_now
      flash[:success] = t('.success')
      redirect_to edit_admin_user_path @user
    else
      flash[:failed] = t('.failed')
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update_attributes admin_update_user_params
      flash[:success] = t('.success')
      redirect_to admin_users_path
    else
      flash[:failed] = t('.failed')
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = t('.success')
    else
      flash[:danger] = t('.failed')
    end
    redirect_to admin_users_path
  end

  private
  def load_user_data
    @user = User.find params[:id]
  end

  def user_params
    password = password_confirmation = Devise.friendly_token.first(8)
    params[:user].merge!({
      password: password,
      password_confirmation: password_confirmation,
      role: User.roles[:mod]
    })
    params.require(:user).permit User::ADMIN_CREATE_ATTRIBUTE
  end

  def admin_update_user_params
    params.require(:user).permit User::UPDATE_ATTRIBUTE
  end
end

app/views/admin/users/edit.html.slim
section.content id='admin-users-edit'
  .row
    .col-md-6
      .box.box-success
        .box-header.with-border
          h3.box-title= t('edit_user')
        .box-body
          = simple_form_for [:admin, @user], defaults: {label: false}, html: {id: "edit-user", multipart: true} do |f|
            .form-group
              - if current_user.admin?
                = f.label :user_role
                = f.select :role, options_for_select([["Moderator", :mod], ["Admin", :admin]], @user.role), {include_blank: "Please select User Role"}, {class: "form-control"}
              = show_field_error f, :role
            .form-group
              = f.label :name, "User name"
              = f.input :name, class: "form-control"
            .form-group.text-center
              = f.submit "Submit", class: "btn btn-block btn-primary"
              = link_to "Cancel", admin_users_path, class: 'btn btn-block btn-danger'

app/views/admin/users/index.html.slim
- provide :title, t('.users')
section.content-header
  = link_to t('.new_user'), new_admin_user_path, class: 'btn bg-purple margin', id: "admin-new-user"
- if @users.any?
  section.content
    .row
      .col-xs-12
        .box.box-info
          .box-header
            h3.box-title
              = t(".user_list")
          .box-body
            table#users-table.table.table-bordered.table-hover
              - thead = [t('.id'), t('.name'), t('.email'), t('.role'), t('.avatar'), t('.actions')]
              thead
                - thead.each do |th|
                  th= th
              tbody
                - @users.each do |user|
                  tr
                    td= user.id
                    td= user.name
                    td= user.email
                    td= user.role
                    td
                      = image_tag 'no_image.png', size: "100x100"
                    td.actions
                      = link_to t('.view'), admin_user_path(user), class: 'btn label label-success'
                      | &nbsp;
                      = link_to t('.edit'), edit_admin_user_path(user), class: 'btn label label-info'
                      | &nbsp;
                      = link_to t('.delete'), admin_user_path(user),
                        method: :delete, data: {confirm: 'Are you sure to delete this user?'},
                        class: 'btn label label-danger'
- else
  p.text-center
    | There are no data

app/views/admin/users/new.html.slim
section.content
  .row
    .col-md-4.col-md-offset-4
      .box.box-success
        .box-header.with-border.text-center
          h3.box-title= t('.create_user')
        .box-body
          = simple_form_for [:admin, @user], defaults: {label: false}, url: admin_users_path do |f|
            .form-group.has-feedback
              = f.input :email, input_html: { class: "form-control" }, placeholder: "Email"
              span.fa.fa-envelope.form-control-feedback
            = f.submit "Create", class: "btn btn-primary btn-block btn-flat"

app/views/admin/users/show.html.slim
- provide :title, t('.user')
section.content#admin-user-profile
  .row
    .col-xs-12
      .box.box-info
        .box-header
          h3.box-title
            = t('.user')
        .box-body
          table.table.table-bordered.table-striped
            tbody
              tr
                td.font-weight-bold= t('.id')
                td= @user.id
              tr
                td.font-weight-bold= t('.email')
                td= @user.email
              tr
                td.font-weight-bold= t('.name')
                td= @user.name
              tr
                td.font-weight-bold= t('.role')
                td= @user.role.capitalize
              tr
                td.font-weight-bold= t('.avatar')
                td
                  - if @user.user_avatar.present?
                    = image_tag @user.user_avatar.url(:thumb)
                  - else
                    = image_tag 'no_image.png', size: "100x100"
              tr
                td colspan="2"
                  = link_to t('.back_to_list'), admin_users_path, class: 'btn btn-success'
                  | &nbsp;
                  = link_to t('.edit'), edit_admin_user_path(@user), class: 'btn btn-info'
                  | &nbsp;
                  = link_to t('.delete'), nil, class: 'btn btn-danger'